export const STAGES = {
  TYPE_OF_USER: 'Are you an NITR Student?',
  NITR_STUDENT_FORM: 'NITR Student Register',
  NON_NITR_STUDENT_FORM: 'Register',
  TXN_SUCCESSFUL: 'Transaction Successful',
  TXN_UNSUCCESSFUL: 'Transaction Unsuccessful',
};

export const INIT_STATE = {
  value: '',
  errorVisibility: false,
  errorMessage: '',
};

export const INPUTS = {
  name: {
    ...INIT_STATE,
    placeholder: 'Name',
    readOnly: false,
    type: 'text',
    inputMode: 'text',
    regex: /[^a-zA-Z_ ]/gi,
    key: 'name',
    show: 'both',
    maxLength: 50,
    minLength: 1,
  },
  email: {
    ...INIT_STATE,
    placeholder: 'Email',
    readOnly: false,
    type: 'text',
    inputMode: 'email',
    regex: '/^[w-.]+@([w-]+.)+[w-]{2,4}$/g',
    key: 'email',
    show: 'both',
    maxLength: 50,
    minLength: 1,
  },
  mobile: {
    ...INIT_STATE,
    placeholder: 'Mobile Number',
    readOnly: false,
    type: 'text',
    inputMode: 'tel',
    regex: /\D/g,
    key: 'mobile',
    show: 'both',
    maxLength: 10,
    minLength: 1,
  },
  gender: {
    ...INIT_STATE,
    placeholder: 'Gender',
    readOnly: false,
    type: 'select',
    inputMode: 'select',
    regex: '',
    key: 'gender',
    show: 'both',
    options: ['Male', 'Female', 'Others'],
    maxLength: 50,
    minLength: 1,
  },
  state: {
    ...INIT_STATE,
    placeholder: 'State',
    readOnly: false,
    type: 'text',
    inputMode: 'text',
    regex: /[^a-zA-Z_ ]/gi,
    key: 'state',
    show: 'non-nitr',
    maxLength: 50,
    minLength: 1,
  },
  city: {
    ...INIT_STATE,
    placeholder: 'City',
    readOnly: false,
    type: 'text',
    inputMode: 'text',
    regex: /[^a-zA-Z_ ]/gi,
    key: 'city',
    show: 'non-nitr',
    maxLength: 50,
    minLength: 1,
  },
  college: {
    ...INIT_STATE,
    placeholder: 'College',
    readOnly: false,
    type: 'text',
    inputMode: 'text',
    regex: /[^a-zA-Z_ ]/gi,
    key: 'college',
    show: 'non-nitr',
    maxLength: 50,
    minLength: 1,
  },
  stream: {
    ...INIT_STATE,
    placeholder: 'Stream',
    readOnly: false,
    type: 'text',
    inputMode: 'text',
    regex: /[^a-zA-Z_ ]/gi,
    key: 'stream',
    show: 'non-nitr',
    maxLength: 50,
    minLength: 1,
  },
  referredBy: {
    ...INIT_STATE,
    placeholder: 'Referred By',
    readOnly: false,
    type: 'text',
    inputMode: 'text',
    regex: '',
    key: 'referredBy',
    show: 'non-nitr',
    maxLength: 50,
    minLength: 1,
  },
  rollNumber: {
    ...INIT_STATE,
    placeholder: 'Roll Number',
    readOnly: false,
    type: 'text',
    inputMode: 'text',
    regex: /[^a-zA-Z0-9_ ]/gi,
    key: 'rollNumber',
    show: 'nitr',
    maxLength: 50,
    minLength: 1,
  },
  password: {
    ...INIT_STATE,
    placeholder: 'Password',
    readOnly: false,
    type: 'password',
    inputMode: 'text',
    regex: '',
    key: 'password',
    show: 'nitr',
    maxLength: 50,
    minLength: 1,
  },
};
