export { default as nav } from './Navigation';
export { default as hero } from './Hero';
export { default as faq } from './FAQ';
export { default as flexData } from './FlexData';
export { default as footer } from './Footer';
export { default as about } from './About';
export { default as events } from './Events';
export { default as caHero } from './CaHero';
export { default as caFlex } from './CaFlex';
