/* eslint-disable max-len */
export default {
  title: 'Our Sponsors',
  alpha: [
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/MLH_xejp6v.png',
      title: 'Title Sponsor',
      name: 'Major League Hacking',
      size: '100%',
      link: 'https://mlh.io/',
      width: '170px',
      alt: 'Major League Hacking',
      color: '#5c9dff',
    },
  ],
  beta: [
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/auth0_ziq5l3.png',
      title: 'Gold Sponsor',
      name: 'Auth0',
      size: '95%',
      link: 'https://a0.to/hacknitr',
      width: '160px',
      alt: 'Auth0',
      color: '#5cffa7',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/auth0_ziq5l3.png',
      title: 'Gold Sponsor',
      name: 'Auth0',
      size: '95%',
      link: 'https://a0.to/hacknitr',
      width: '160px',
      alt: 'Auth0',
      color: '#735cff',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/auth0_ziq5l3.png',
      title: 'Gold Sponsor',
      name: 'Auth0',
      size: '95%',
      link: 'https://a0.to/hacknitr',
      width: '160px',
      alt: 'Auth0',
      color: '#e85cff',
    },
  ],
  gamma: [
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/auth0_ziq5l3.png',
      title: 'Silver Sponsor',
      name: 'Auth0',
      size: '95%',
      link: 'https://a0.to/hacknitr',
      width: '160px',
      alt: 'Auth0',
      color: '#5cffa7',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/auth0_ziq5l3.png',
      title: 'Silver Sponsor',
      name: 'Auth0',
      size: '95%',
      link: 'https://a0.to/hacknitr',
      width: '160px',
      alt: 'Auth0',
      color: '#735cff',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/auth0_ziq5l3.png',
      title: 'Silver Sponsor',
      name: 'Auth0',
      size: '95%',
      link: 'https://a0.to/hacknitr',
      width: '160px',
      alt: 'Auth0',
      color: '#e85cff',
    },
  ],
};
